LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := icu
LOCAL_SRC_FILES :=  \
    appendable.cpp \
    bmpset.cpp \
    brkeng.cpp \
    brkiter.cpp \
    bytestream.cpp \
    bytestrie.cpp \
    bytestriebuilder.cpp \
    bytestrieiterator.cpp \
    caniter.cpp \
    chariter.cpp \
    charstr.cpp \
    cmemory.c \
    cstring.c \
    cwchar.c \
    dictbe.cpp \
    dictionarydata.cpp \
    dtintrv.cpp \
    errorcode.cpp \
    filterednormalizer2.cpp \
    icudataver.c \
    icuplug.c \
    listformatter.cpp \
    locavailable.cpp \
    locbased.cpp \
    locdispnames.cpp \
    locid.cpp \
    loclikely.cpp \
    locmap.c \
    locresdata.cpp \
    locutil.cpp \
    messagepattern.cpp \
    mutex.cpp \
    normalizer2.cpp \
    normalizer2impl.cpp \
    normlzr.cpp \
    parsepos.cpp \
    patternprops.cpp \
    propname.cpp \
    propsvec.c \
    punycode.cpp \
    putil.cpp \
    rbbi.cpp \
    rbbidata.cpp \
    rbbinode.cpp \
    rbbirb.cpp \
    rbbiscan.cpp \
    rbbisetb.cpp \
    rbbistbl.cpp \
    rbbitblb.cpp \
    resbund.cpp \
    resbund_cnv.cpp \
    ruleiter.cpp \
    schriter.cpp \
    serv.cpp \
    servlk.cpp \
    servlkf.cpp \
    servls.cpp \
    servnotf.cpp \
    servrbf.cpp \
    servslkf.cpp \
    stringpiece.cpp \
    stringtriebuilder.cpp \
    uarrsort.c \
    ubidi.c \
    ubidi_props.c \
    ubidiln.c \
    ubidiwrt.c \
    ubrk.cpp \
    ucase.cpp \
    ucasemap.cpp \
    ucasemap_titlecase_brkiter.cpp \
    ucat.c \
    uchar.c \
    ucharstrie.cpp \
    ucharstriebuilder.cpp \
    ucharstrieiterator.cpp \
    uchriter.cpp \
    ucln_cmn.c \
    ucmndata.c \
    ucnv.c \
    ucnv2022.cpp \
    ucnv_bld.cpp \
    ucnv_cb.c \
    ucnv_cnv.c \
    ucnv_ct.c \
    ucnv_err.c \
    ucnv_ext.cpp \
    ucnv_io.cpp \
    ucnv_lmb.c \
    ucnv_set.c \
    ucnv_u16.c \
    ucnv_u32.c \
    ucnv_u7.c \
    ucnv_u8.c \
    ucnvbocu.cpp \
    ucnvdisp.c \
    ucnvhz.c \
    ucnvisci.c \
    ucnvlat1.c \
    ucnvmbcs.c \
    ucnvscsu.c \
    ucnvsel.cpp \
    ucol_swp.cpp \
    udata.cpp \
    udatamem.c \
    udataswp.c \
    uenum.c \
    uhash.c \
    uhash_us.cpp \
    uidna.cpp \
    uinit.c \
    uinvchar.c \
    uiter.cpp \
    ulist.c \
    uloc.cpp \
    uloc_tag.c \
    umapfile.c \
    umath.c \
    umutex.cpp \
    unames.cpp \
    unifilt.cpp \
    unifunct.cpp \
    uniset.cpp \
    uniset_closure.cpp \
    uniset_props.cpp \
    unisetspan.cpp \
    unistr.cpp \
    unistr_case.cpp \
    unistr_case_locale.cpp \
    unistr_cnv.cpp \
    unistr_props.cpp \
    unistr_titlecase_brkiter.cpp \
    unorm.cpp \
    unorm_it.c \
    unormcmp.cpp \
    uobject.cpp \
    uprops.cpp \
    ures_cnv.c \
    uresbund.cpp \
    uresdata.c \
    usc_impl.c \
    uscript.c \
    uscript_props.cpp \
    uset.cpp \
    uset_props.cpp \
    usetiter.cpp \
    ushape.cpp \
    usprep.cpp \
    ustack.cpp \
    ustr_cnv.c \
    ustr_titlecase_brkiter.cpp \
    ustr_wcs.cpp \
    ustrcase.cpp \
    ustrcase_locale.cpp \
    ustrenum.cpp \
    ustrfmt.c \
    ustring.cpp \
    ustrtrns.cpp \
    utext.cpp \
    utf_impl.c \
    util.cpp \
    util_props.cpp \
    utrace.c \
    utrie.cpp \
    utrie2.cpp \
    utrie2_builder.cpp \
    uts46.cpp \
    utypes.c \
    uvector.cpp \
    uvectr32.cpp \
    uvectr64.cpp \
    wintz.c \
    alphaindex.cpp \
    anytrans.cpp \
    astro.cpp \
    basictz.cpp \
    bocsu.cpp \
    brktrans.cpp \
    buddhcal.cpp \
    calendar.cpp \
    casetrn.cpp \
    cecal.cpp \
    chnsecal.cpp \
    choicfmt.cpp \
    coleitr.cpp \
    coll.cpp \
    compactdecimalformat.cpp \
    coptccal.cpp \
    cpdtrans.cpp \
    csdetect.cpp \
    csmatch.cpp \
    csr2022.cpp \
    csrecog.cpp \
    csrmbcs.cpp \
    csrsbcs.cpp \
    csrucode.cpp \
    csrutf8.cpp \
    curramt.cpp \
    currfmt.cpp \
    currpinf.cpp \
    currunit.cpp \
    dangical.cpp \
    datefmt.cpp \
    dcfmtsym.cpp \
    decContext.c \
    decNumber.c \
    decfmtst.cpp \
    decimfmt.cpp \
    digitlst.cpp \
    dtfmtsym.cpp \
    dtitvfmt.cpp \
    dtitvinf.cpp \
    dtptngen.cpp \
    dtrule.cpp \
    esctrn.cpp \
    ethpccal.cpp \
    fmtable.cpp \
    fmtable_cnv.cpp \
    format.cpp \
    fphdlimp.cpp \
    fpositer.cpp \
    funcrepl.cpp \
    gender.cpp \
    gregocal.cpp \
    gregoimp.cpp \
    hebrwcal.cpp \
    identifier_info.cpp \
    indiancal.cpp \
    inputext.cpp \
    islamcal.cpp \
    japancal.cpp \
    locdspnm.cpp \
    measfmt.cpp \
    measure.cpp \
    msgfmt.cpp \
    name2uni.cpp \
    nfrs.cpp \
    nfrule.cpp \
    nfsubs.cpp \
    nortrans.cpp \
    nultrans.cpp \
    numfmt.cpp \
    numsys.cpp \
    olsontz.cpp \
    persncal.cpp \
    plurfmt.cpp \
    plurrule.cpp \
    quant.cpp \
    rbnf.cpp \
    rbt.cpp \
    rbt_data.cpp \
    rbt_pars.cpp \
    rbt_rule.cpp \
    rbt_set.cpp \
    rbtz.cpp \
    regexcmp.cpp \
    regeximp.cpp \
    regexst.cpp \
    regextxt.cpp \
    region.cpp \
    reldtfmt.cpp \
    rematch.cpp \
    remtrans.cpp \
    repattrn.cpp \
    scriptset.cpp \
    search.cpp \
    selfmt.cpp \
    simpletz.cpp \
    smpdtfmt.cpp \
    smpdtfst.cpp \
    sortkey.cpp \
    strmatch.cpp \
    strrepl.cpp \
    stsearch.cpp \
    taiwncal.cpp \
    tblcoll.cpp \
    timezone.cpp \
    titletrn.cpp \
    tmunit.cpp \
    tmutamt.cpp \
    tmutfmt.cpp \
    tolowtrn.cpp \
    toupptrn.cpp \
    translit.cpp \
    transreg.cpp \
    tridpars.cpp \
    tzfmt.cpp \
    tzgnames.cpp \
    tznames.cpp \
    tznames_impl.cpp \
    tzrule.cpp \
    tztrans.cpp \
    ucal.cpp \
    ucln_in.c \
    ucol.cpp \
    ucol_bld.cpp \
    ucol_cnt.cpp \
    ucol_elm.cpp \
    ucol_res.cpp \
    ucol_sit.cpp \
    ucol_tok.cpp \
    ucol_wgt.cpp \
    ucoleitr.cpp \
    ucsdet.cpp \
    ucurr.cpp \
    udat.cpp \
    udateintervalformat.cpp \
    udatpg.cpp \
    ulocdata.c \
    umsg.cpp \
    unesctrn.cpp \
    uni2name.cpp \
    unum.cpp \
    upluralrules.cpp \
    uregex.cpp \
    uregexc.cpp \
    usearch.cpp \
    uspoof.cpp \
    uspoof_build.cpp \
    uspoof_conf.cpp \
    uspoof_impl.cpp \
    uspoof_wsconf.cpp \
    utmscale.c \
    utrans.cpp \
    vtzone.cpp \
    vzone.cpp \
    windtfmt.cpp \
    winnmfmt.cpp \
    wintzimpl.cpp \
    zonemeta.cpp \
    zrule.cpp \
    ztrans.cpp \
    
LOCAL_CFLAGS := -DU_I18N_IMPLEMENTATION -DU_COMMON_IMPLEMENTATION -I${MY_FRAMEWORKS_PATH}/frameworks -I${MY_FRAMEWORKS_PATH}/frameworks/include
LOCAL_LDFLAGS := -v -L${MY_FRAMEWORKS_PATH}/frameworks/libs
#LOCAL_LDLIBS := -lgnustl_shared
include $(BUILD_SHARED_LIBRARY)
#include $(BUILD_STATIC_LIBRARY)
