
LIB_NAME=expat
CFLAGS=-DHAVE_EXPAT_CONFIG_H
LDLIBS=
LDFLAGS=-v -Wl,--no-undefined
OBJECTS = \
    xmlparse.o \
    xmltok.o \
    xmlrole.o \
    
include ${MYOS_PATH}/android/sdk/resources/makefile-static
