#
# Copyright 2014 myOS Group. All rights reserved.
#

LIB_NAME=MAKit
CFLAGS=-DDEBUG -I$(ANDROID_SOURCE_PATH)/device/generic/goldfish/opengl/system -I$(ANDROID_SOURCE_PATH)/development/tools/emulator/opengl/host/include/libOpenglRender -I${MY_FRAMEWORKS_PATH}/libraries/MAOpenglCodecCommon
OBJECTS=MABufferProducer.o MABufferQueue.o MAWindow.o MAWindowHook.o
include ${MY_FRAMEWORKS_PATH}/resources/makefile-static
