
LIB_NAME=png
#CFLAGS=-DDEBUG
#LDLIBS= -lz
#LDFLAGS=-v -Wl,--no-undefined
OBJECTS = \
	png.o \
	pngerror.o \
	pnggccrd.o \
	pngget.o \
	pngmem.o \
	pngpread.o \
	pngread.o \
	pngrio.o \
	pngrtran.o \
	pngrutil.o \
	pngset.o \
	pngtrans.o \
	pngvcrd.o \
	pngwio.o \
	pngwrite.o \
	pngwtran.o \
	pngwutil.o \

include ${MY_FRAMEWORKS_PATH}/resources/makefile-static
