
LIB_NAME=fontconfig
CFLAGS=-DHAVE_CONFIG_H -DDEBUG -DFONTCONFIG_PATH='"/system/fonts"' -DFC_CACHEDIR='"cache"'

#ARLIBS=-lfreetype -lexpat -llog

OBJECTS = \
    fcatomic.o \
    fcblanks.o \
    fccfg.o \
    fccharset.o \
    fccompat.o \
    fcdbg.o \
    fcdefault.o \
    fcdir.o \
    fcformat.o \
    fcfreetype.o \
    fcfs.o \
    fchash.o \
    fcinit.o \
    fclang.o \
    fclist.o \
    fcmatch.o \
    fcmatrix.o \
    fcname.o \
    fcobjs.o \
    fcpat.o \
    fcserialize.o \
    fcstat.o \
    fcstr.o \
    ftglue.o \
    fcxml.o \
    fccache.o \

include ${MY_FRAMEWORKS_PATH}/resources/makefile-static
