
LIB_NAME=MAOpenglCodecCommon
CFLAGS=-DDEBUG -I${MY_FRAMEWORKS_PATH}/libraries/MAOpenglCodecCommon -I$(ANDROID_SOURCE_PATH)/development/tools/emulator/opengl/host/include/libOpenglRender

OBJECTS = \
    GLSharedGroup.o \
    GLClientState.o \
    glUtils.o \

include ${MYOS_PATH}/android/sdk/resources/makefile-static
