#
# Copyright 2014 myOS Group. All rights reserved.
#

LIB_NAME=MARenderControl_enc
CFLAGS=-DDEBUG -I$(ANDROID_SOURCE_PATH)/development/tools/emulator/opengl/host/include/libOpenglRender -I${MY_FRAMEWORKS_PATH}/libraries/MAOpenglCodecCommon

OBJECTS=renderControl_client_context.o renderControl_enc.o

include ${MYOS_PATH}/android/sdk/resources/makefile-static
