
LIB_NAME=MAGLESv1_enc
CFLAGS=-DDEBUG -I$(ANDROID_SOURCE_PATH)/development/tools/emulator/opengl/host/include/libOpenglRender -I${MY_FRAMEWORKS_PATH}/libraries/MAOpenglCodecCommon

OBJECTS = \
    GLEncoder.o \
    gl_entry.o \
    GLEncoderUtils.o \
    gl_enc.o \

include ${MYOS_PATH}/android/sdk/resources/makefile-static
