
LIB_NAME=pixman
CFLAGS=-DHAVE_CONFIG_H
LDLIBS=
LDFLAGS=-v -Wl,--no-undefined
OBJECTS = \
	pixman.o \
	pixman-access.o \
	pixman-access-accessors.o \
	pixman-bits-image.o \
	pixman-combine32.o \
	pixman-combine-float.o \
	pixman-conical-gradient.o \
	pixman-filter.o \
	pixman-x86.o \
	pixman-mips.o \
	pixman-arm.o \
	pixman-ppc.o \
	pixman-edge.o \
	pixman-edge-accessors.o \
	pixman-fast-path.o \
	pixman-glyph.o \
	pixman-general.o \
	pixman-gradient-walker.o \
	pixman-image.o \
	pixman-implementation.o \
	pixman-linear-gradient.o \
	pixman-matrix.o \
	pixman-noop.o \
	pixman-radial-gradient.o \
	pixman-region16.o \
	pixman-region32.o \
	pixman-solid-fill.o \
	pixman-timer.o \
	pixman-trap.o \
	pixman-utils.o \

include ${MYOS_PATH}/android/sdk/resources/makefile-static
