
LIB_NAME=lcms
CFLAGS=-DPACKAGE_NAME=\"lcms\" -DPACKAGE_TARNAME=\"lcms\" -DPACKAGE_VERSION=\"1.19\" -DPACKAGE_STRING=\"lcms\ 1.19\" -DPACKAGE_BUGREPORT=\"\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DSIZEOF_INT=4 -DSIZEOF_UNSIGNED_INT=4 -DSIZEOF_LONG=4 -DSIZEOF_UNSIGNED_LONG=4 -DSIZEOF_LONG_LONG=8 -DSIZEOF_UNSIGNED_LONG_LONG=8 -DHasJPEG=1 -DHasZLIB=1 -DHasTIFF=1 -DHAVE_TIFFCONF_H=1
LDLIBS=
LDFLAGS=-v -Wl,--no-undefined
OBJECTS = \
    cmscnvrt.o \
    cmserr.o \
    cmsgamma.o \
    cmsgmt.o \
	cmsintrp.o \
    cmsio0.o \
    cmsio1.o \
    cmslut.o \
    cmsmatsh.o \
	cmsmtrx.o \
    cmspack.o \
    cmspcs.o \
    cmswtpnt.o \
    cmsxform.o \
	cmssamp.o \
    cmscam97.o \
    cmsnamed.o \
    cmsps2.o \
    cmscam02.o \
	cmsvirt.o \
    cmscgats.o \

include ${MY_FRAMEWORKS_PATH}/resources/makefile-static
